//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ImdbApiBackEnd
{
    using System;
    using System.Collections.Generic;
    
    public partial class Film4
    {
        public string ImdbID { get; set; }
        public string Title { get; set; }
        public string Plot { get; set; }
        public int id { get; set; }
    }
}
